name: Check External Hyperlinks

on:
  workflow_dispatch:
  page_build:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run lychee to check for wrong external links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --exclude-all-private --no-progress --mode color --accept 100..=103,200..=299,301..=303,307,308,403,412,429 --quiet --exclude '^mailto:' --exclude '^[/#]' --exclude '^https://ondemand\.hpc\.taltech\.ee'

